name: Automatischer Aufbau (Deploy)

on:
  push:
    branches:
      - main

jobs:
  deploy-anwendung:
    runs-on: ubuntu-latest
    steps:
      - name: Code herunterladen
        uses: actions/checkout@v4

      - name: Kubernetes Kontext setzen
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          # Hier holt sich der Roboter deinen geheimen Schlüssel aus dem GitHub-Tresor
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Bauplan anwenden
        uses: Azure/k8s-deploy@v4
        with:
          # Der Bereich in deinem Cluster
          namespace: stahlbeton-sm0810
          # Die Datei, die angewendet werden soll
          manifests: |
            k8s-anwendung.yaml