name: Automatischer Aufbau (Deploy)

on:
  push:
    branches:
      - main
  # Manueller Startknopf
  workflow_dispatch: 

jobs:
  deploy-anwendung:
    runs-on: ubuntu-latest
    steps:
      - name: Code herunterladen
        uses: actions/checkout@v3

      # Direkter Zugang über unseren KUBE_CONFIG Schlüssel (Plan C)
      # Kein Azure-Login mehr notwendig!
      - name: Kubernetes Kontext setzen
        uses: azure/k8s-set-context@v3
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      # Unseren Bauplan (YAML) auf dem Computer ausführen
      - name: Bauplan anwenden
        uses: Azure/k8s-deploy@v4
        with:
          namespace: 'stahlbeton-sm0810'
          manifests: |
            k8s-anwendung.yaml